[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "seqparser"
authors = [{name = "JoeVonDahab", email = "youssef.nageh@live.com"}]
readme = "README.md"
dynamic = ["version", "description"]
